import { ReactNode } from 'react'
import './globals.css'
import Header from '@/components/header'
import Navbar from '@/components/navbar'
import Providers from '@/components/providers'
import SearchBox from '@/components/searchBox'

export const metadata = {
  title: 'Imdb Clone',
  description: 'Generated by create next app',
}

type Children = {
  children: ReactNode
}

const RootLayout = ({ children }: Children) => {
  return (
    <html lang='en'>
      <body>
        <Providers>
          <Header />
          <Navbar />
          <SearchBox />
          {children}
        </Providers>
      </body>
    </html>
  )
}

export default RootLayout
