import { ReactNode } from 'react'
import './globals.css'
import Header from './header'
import Providers from './porviders'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Children = {
  children: ReactNode
}

const RootLayout = ({ children }: Children) => {
  return (
    <html lang='en'>
      <body>
        <Providers>
          {/* Header */}
          <Header />
          {/* Navbar */}
          {/* Searchbox */}

          {children}
        </Providers>
      </body>
    </html>
  )
}

export default RootLayout
