import { ReactNode } from 'react'
import './globals.css'
import Header from './header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Children = {
  children: React.ReactNode
}

const RootLayout = ({ children }: Children) => {
  return (
    <html lang='en'>
      <body>
        {/* Header */}
        <Header />
        {/* Navbar */}
        {/* Searchbox */}

        {children}
      </body>
    </html>
  )
}

export default RootLayout
